CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30),
    PACKAGE_ID NUMBER(10),
    CURRENT_INVENTORY_COUNT NUMBER(5),
    STORE_COST NUMBER(10, 2),
    SALE_PRICE NUMBER(10, 2),
    LAST_UPDATE_DATE DATE,
    UPDATED_BY_USER VARCHAR2(30),
    PET_FLAG VARCHAR2(1),
    CONSTRAINT fk_product_package 
        FOREIGN KEY (PACKAGE_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE CUSTOMER (
    CUST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRSTNAME VARCHAR2(20),
    LASTNAME VARCHAR2(25),
    ADDRESS VARCHAR2(32),
    CITY VARCHAR2(20),
    STATE VARCHAR2(2),
    ZIP VARCHAR2(9)
);

CREATE TABLE CUSTOMER_SALE (
    SALES_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUST_ID NUMBER(10),
    TOTAL_ITEM_AMOUNT NUMBER(10, 2),
    TAX_AMOUNT NUMBER(10, 2),
    TOTAL_SALE_AMOUNT NUMBER(10, 2),
    SALES_DATE DATE,
    SHIPPING_HANDLING_FEE NUMBER(5, 2),
    CONSTRAINT fk_sale_customer 
        FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

CREATE TABLE SALES_ITEM (
    SALES_ID NUMBER,
    PRODUCT_ID NUMBER,
    SALE_AMOUNT NUMBER(10, 2),
    CONSTRAINT pk_sales_item PRIMARY KEY (SALES_ID, PRODUCT_ID),
    CONSTRAINT fk_sales_item_sale FOREIGN KEY (SALES_ID) 
        REFERENCES CUSTOMER_SALE(SALES_ID),
    CONSTRAINT fk_sales_item_product FOREIGN KEY (PRODUCT_ID) 
        REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE PET_CARE_LOG (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID NUMBER,
    LOG_DATETIME DATE,
    CREATED_BY_USER VARCHAR2(30),
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE,
    CONSTRAINT fk_pet_product FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);


-- trigger 1
CREATE OR REPLACE TRIGGER trg_pet_care_log_bi
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
    :NEW.CREATED_BY_USER := USER;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Error in trg_pet_care_log_bi: ' || SQLERRM
        );
END;
/

-- trigger 2
CREATE OR REPLACE TRIGGER trg_pet_care_log_bu
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != :OLD.CREATED_BY_USER THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Update not allowed'
        );
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Error in trg_pet_care_log_bu: ' || SQLERRM
        );
END;
/


-- trigger 3
CREATE OR REPLACE TRIGGER trg_pet_care_log_bd
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'only JOEMANAGER can delete rows'
        );
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20005,
            'Error in trg_pet_care_log_bd: ' || SQLERRM
        );
END;
/